### PR TITLE
created short running turn key test as a copy of 'alg_params/valid_mi…

### PR DESCRIPTION
**Pull request by peterjcarr**
gpunit, added short running sanity check test

I added a provisional 'gpunit' folder which includes one test that I can use as a sanity check. It follows a few guidelines which make it easier for me (and other GP server admins) to test a module without making any customizations (such as setting config properties, mounting remote directories or copying data files from remote sites).

Feel free to suggest a different test to use as the sanity check.

### CODE REVIEW

**Comment by peterjcarr** [comment]
I used a slightly modified version of the expected output file 'P53_14samples_collapsed_symbols.PROJ.gct', here are the diffs (only two fields were different and only by one digit in least significant figure).
[diffs.txt](https://github.com/GSEA-MSigDB/ssGSEAProjection-gpmodule/files/2448684/diffs.txt)

**Comment by peterjcarr** [comment]
the simple diff is not working; when I run the test on cloud.gp it is an exact match to the previous version of the expected output file. when I run on my local mac server I need to diff with the newer version. this surprises me because I would have expected the same results because we are presumably using the same container.

**Comment by peterjcarr** [comment]
Hi David, I just realized I was running the tests locally (not in a docker container) ... I am double checking everything in a container now.

**Comment by davideby** [comment]
OK, just let me know when you've verified that.

**Comment by peterjcarr** [comment]
I confirmed that the tests pass in both a local docker container and in docker via beta.gp and AWS Batch. I will go ahead and delete this pull request.

**Comment by peterjcarr** [comment]
correction! You should accept this pull request. I reverted back to the original data file. Now things are working as expected in docker, both locally and on AWS Batch. Please accept this so that I have an easy way to run a short running test.
Thanks,
Peter

**Pull request merged**
